#!/usr/bin/env sh
# creates symlinks to the dotfiles in this folder
dir=~/dotfiles
olddir=~/dotfiles-old
files="bashrc vimrc gitconfig"
echo "Creating backup dotfiles folder $olddir"
mkdir -p $olddir
echo "Creating symlinks for:"
cd $dir
for file in $files
do
	echo "$file"
	if test -f ~/.$file || test -d ~/.$file
	then
		mv ~/.$file $olddir/.$file
	fi
	ln -s $dir/$file ~/.$file
done
